#!/bin/bash
ip=$1
changed=$2
#oldip="31.24.8.137"
source /etc/dnsexitoldip

if [ $changed -eq 0 ]; then
#  pushbullet push all link "meosch.tk ip did not change. ip is still:" http://$ip >&2>/tmp/dnsexitpushbullet.txt
  exit
else
  pushbullet push all link "meosch.tk ip change, is now:" http://$ip >&2>/tmp/dnsexitpushbullet.txt
fi
